


[env:esp8266]
platform = espressif8266
board = nodemcuv2
framework = arduino
build_flags = 
	-DESP8266
	-DMODULE_SMARTPLUG
	#-DMODULE_VEILLEUSE

lib_deps = 
	knolleary/PubSubClient@^2.8
	bblanchon/ArduinoJson@^7.4.2
	marcoschwartz/LiquidCrystal_I2C@^1.1.4
	adafruit/Adafruit Unified Sensor@^1.1.15
	adafruit/DHT sensor library@^1.4.6


[env:esp32]
platform = espressif32
board = nodemcu-32s
framework = arduino
build_flags = 
	-DESP32
	-DLATENCY_TEST
	#-DMODULE_SENTINEL
lib_deps = 
	knolleary/PubSubClient@^2.8
	bblanchon/ArduinoJson@^7.4.2
	marcoschwartz/LiquidCrystal_I2C@^1.1.4
	adafruit/Adafruit Unified Sensor@^1.1.15
	adafruit/DHT sensor library@^1.4.6